export type CliErrorCode =
  | "USAGE_ERROR"
  | "CONFIG_READ_ERROR"
  | "CONFIG_PARSE_ERROR"
  | "CONFIG_VALIDATION_ERROR"
  | "ARTIFACT_SCHEMA_INVALID"
  | "OUT_DIR_NON_EMPTY"
  | "ARTIFACT_WRITE_ERROR";
